---
abstract: 'Pluggable POE event emitter role for cows'
author:
  - 'Jon Portnoy <avenj@cobaltirc.org>'
build_requires:
  Test::Exception: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooX-Role-POE-Emitter
requires:
  Carp: 0
  Moo: 1
  Moo::Role: 0
  MooX::Role::Pluggable: 0.12
  POE: 0
  Scalar::Util: 0
  Try::Tiny: 0
  Type::Tiny: 0.022
  Types::Standard: 0
  perl: v5.10.1
  strictures: 1
resources:
  repository: git://github.com/avenj/moox-role-poe-emitter.git
version: 0.120002
