---
abstract: 'Pluggable POE event emitter role for cows'
author:
  - 'Jon Portnoy <avenj@cobaltirc.org>'
build_requires:
  ExtUtils::MakeMaker: 0
  File::Spec: 0
  List::Util: 0
  Scalar::Util: 0
  Test::Exception: 0
  Test::More: 0.88
  version: 0.77
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooX-Role-POE-Emitter
requires:
  Carp: 0
  Class::Method::Modifiers: 0
  List::Objects::Types: 1
  List::Objects::WithUtils: 2.007
  Moo: 1
  Moo::Role: 0
  MooX::Role::Pluggable: 0.12
  MooX::late: 0.014
  POE: 0
  Scalar::Util: 0
  Try::Tiny: 0
  Type::Tiny: 0.022
  Types::Standard: 0
  perl: v5.10.1
  strictures: 1
resources:
  repository: git://github.com/avenj/moox-role-poe-emitter.git
version: 1.001001
